### ISSUE TITLE
Warning: getFieldDecorator will override value, so please don't set value directly and use setFieldsValue to set it.

### ISSUE THREAD

**Issue by navono** [haozhaohang/ant-design-expand-component#1]
应该将自定义控件的中的`value`属性删除。然后在`getFieldDecorator`的时候，设置`initialValue`。
见[3976](https://github.com/ant-design/ant-design/issues/3976)

**Comment by haozhaohang** [comment]
已经修改！感谢

**Comment by aswin2772** [comment]
The value attribute in the custom control should be removed. Then in the getFieldDecorator, set initialValue.

**Comment by nyj000** [comment]
What should I do when I want to use v-model and getFieldDecorator in  another places?
